name: chess

common:
  # Renderer
  renderer:
    renderState:        true
    renderValidActions: false
    renderActionPlayed: true
    renderResult:       true
    
  # Model
  model:
    autoInitialState: true

    maxNodes:   1000000
    maxSamples: 1

    numThreads: 4
    mctsBatchSize: 64
    historySize: 8
    maxDepth: 100

    cPUCT:    1.5
    virtualLoss: 1
    keepK:    5

  # Inference
  inference:
    numHumans: 0

  # Training
  training:
    bufferSize:        10000
    trainingBatchSize: 64
    learningRate:      0.001
    epochs:            100

gameSpecific:
  # ChessRenderer specific
  whiteAtBottom:   true
  showCoordinates: true
  renderRawState:  false
  